shop/urls.py
from django.urls import path
from . import views




app_name='shop'

urlpatterns=[
    path('',views.home,name='home'),
    path('register',views.register,name='register'),
    path('login',views.login_page,name='login'),
    path('logout',views.logout_page,name='logout'),
    path('cart',views.cart_page,name='cart'),

    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('add_to_wishlist/<int:product_id2>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_wishlist/<int:wid>',views.remove_wishlist,name='remove_wishlist'),

    path('remove_cart/<str:cid>',views.remove_cart,name='remove_cart'),
    path('collections',views.collections,name='collections'),
    path('collections/<str:name>',views.collectionsview,name='collections'),
    path('collections/<str:cname>/<str:pname>',views.product_details,name='product_details'),
    path('addtocart/<int:product_id>',views.add_to_cart,name="addtocart"),
    path('payment',views.payment,name='payment'),
    path('about',views.about,name='about'),
    path('contact',views.contact,name='contact'),
    
]

shopfusion/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.http import HttpResponse
from django.contrib.auth.models import User
import datetime
from django.conf import settings
import os

# Create your models here.
def get_file_name(requset,filename):
  now_time=datetime.datetime.now().strftime("%Y%m%d%H%M%S")
  new_filename="%s%s"%(now_time,filename)
  return os.path.join(settings.MEDIA_ROOT,'uploads/',new_filename)



class Catagory(models.Model):
    name=models.CharField(max_length=150,null=False,blank=False)
    image=models.ImageField(upload_to=get_file_name,null=True,blank=True)
    description=models.TextField(max_length=500,null=False,blank=False)
    status=models.BooleanField(default=False,help_text='0-show,1-Hidden')
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    category=models.ForeignKey(Catagory,on_delete=models.CASCADE)
    name=models.CharField(max_length=150,null=False,blank=False)
    vendor=models.CharField(max_length=150,null=False,blank=False)
    product_image=models.ImageField(upload_to=get_file_name,null=True,blank=True)
    quantity=models.IntegerField(null=False,blank=False)
    original_price=models.FloatField(null=False,blank=False)
    selling_price=models.FloatField(null=False,blank=False)
    description=models.TextField(max_length=500,null=False,blank=False)
    status=models.BooleanField(default=False,help_text='0-show,1-Hidden')
    trending=models.BooleanField(default=False,help_text='0-default,1-Trending')
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    product_qty=models.IntegerField(null=False,blank=False)
    created_at=models.DateTimeField(auto_now_add=True,null=True)

    @property
    def total_cost(self):
        return self.product_qty*self.products.selling_price
    

class WishlistItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)

    
    class Meta:
        unique_together = ('user', 'product')

    

shop/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
from shop.form import CustomUserForm
from .models import *
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
import json
from .models import Cart
from .models import Product
from django.contrib.auth.decorators import login_required




# Create your views here.

def home(request):
    products=Product.objects.filter(trending=1)
    return render(request,'shop/index.html',{'products':products})


def cart_page(request):
   cart_items=Cart.objects.all()
   total_price=sum(item.products.original_price*item.product_qty for item in cart_items)
   total_price_per_item=[]
   grand_total=0
   for item in cart_items:
      item_total=item.products.original_price*item.product_qty
      total_price_per_item.append({'item':item,'total':'item_total'})
      grand_total+=item_total

      return render(request,'shop/cart.html',{'cart_items':cart_items,'grand_total':grand_total,'total_price':total_price})
   return render(request,'shop/cart.html')


def remove_cart(request,cid):
   cartitem=Cart.objects.get(id=cid)
   cartitem.delete()
   return redirect('/cart')





def add_to_cart(request,product_id):
    if request.method=='POST':
      qty=request.POST['quantity']
      product=Product.objects.get(id=product_id)
      cart_item,created=Cart.objects.get_or_create(products=product,product_qty=qty)
      if not created:
         cart_item.product_qty+=1
         cart_item.save()
         messages.success(request,"added to cart")
      return redirect('shop:cart')


@login_required
def wishlist_view(request):
    wishlist_items = WishlistItem.objects.filter(user=request.user)
    return render(request, 'shop/wishlist.html', {'wishlist_items': wishlist_items})

@login_required
def add_to_wishlist(request, product_id2):
     product = Product.objects.get(id=product_id2)
     WishlistItem.objects.get_or_create(user=request.user, product=product)
    
     return redirect('shop:wishlist')

def remove_wishlist(request,wid):
   item=WishlistItem.objects.get(id=wid)
   item.delete()
   return redirect('shop:wishlist')
   
    

def logout_page(request):
   if request.user.is_authenticated:
      logout(request)
      messages.success(request,'Logged out Successfully')
      return redirect("/")

def login_page(request):
    if request.user.is_authenticated:
       return redirect("/")
    else:
     if request.method=='POST':
      name=request.POST.get('username')
      pwd=request.POST.get('password')
      user=authenticate(request,username=name,password=pwd)
      if user is not None:
        login(request,user)
        messages.success(request,"Logged in Successfully")
        return redirect("/")
      else:
        messages.error(request,"Invalid User Name or Password")
        return redirect("/login")
    return render(request,"shop/login.html")
 
     
def register(request):
    form=CustomUserForm()
    if request.method=='POST':
       form=CustomUserForm(request.POST)
       if form.is_valid():
          form.save()
          messages.success(request,'Registration Success You Can Login Now..!')
          return redirect('/login')
    return render(request,'shop/register.html',{'form':form})

def collections(request):
    catagory=Catagory.objects.filter(status=0)
    return render(request,'shop/collections.html',{'catagory':catagory})

def collectionsview(request,name):
  if(Catagory.objects.filter(name=name,status=0)):
        products=Product.objects.filter(category__name=name)
        return render(request,'shop/products/index.html',{'products':products,'category_name':name})
  else:
    messages.warning(request,'NOs such category found')
    return redirect('collections')
  
def product_details(request,cname,pname):
    if(Catagory.objects.filter(name=cname,status=0)):
      if(Product.objects.filter(name=pname,status=0)):
        products=Product.objects.filter(name=pname,status=0).first()
        return render(request,"shop/products/product_details.html",{"products":products})
      else:
        messages.error(request,"No Such Produtct Found")
        return redirect('collections')
    else:
      messages.error(request,"No Such Catagory Found")
      return redirect('collections')
    

def payment(request):
   return render (request,'shop/payment.html')    

def about(request):
   return render (request,'shop/about.html')

def contact(request):
   return render (request,'shop/contact.html')

shop/templates/shop/cart.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
Registration | shopkart
{% endblock title %}

{% block content %}
<style>
.pay{
  position: relative;
  top:50%;
  background-color:#0a0a23;
  color: #fff;
  border:none;
  border-radius:10px;
  box-shadow: 0px 0px 2px 2px rgb(0,0,0);
  width: 100px;
  height: 40px;
  padding: 10px;
  box-shadow: inset;


}
</style>



<section class="bg-light py-4 my-5" style="min-height:600px;">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3">Cart item</h4>
        <hr style="border-color:#b8bfc2;">
        <img src="{{products.product_image.url}}" height="300px" class="card-image-top" alt="{{products}}">
      </div>

     
       <table class="">
          <tr>
              <th>image</th>
              <th>product name</th>
              <th>unit</th>
              <th>quantity</th>
              <th>amount</th>
              <th>remove</th>
          </tr>
         {% for item in cart_items %}
         <tr>
          <td><img src="{{item.products.product_image.url}}" height="80px"  alt="{{item.products.name}}"></td>
          <td>{{item.products.name}}</td>
          <td>{{item.products.selling_price | stringformat:'d'}}</td>
          <td>{{item.product_qty}}</td>
          <td class="amt">{{item.total_cost | stringformat:'d'}}</td>
          <td><a href="{% url 'shop:remove_cart'  item.id %}" onclick="return confirm('Are you sure? to Remove')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i>Remove</a></td>
         </tr>

        {% endfor %}

          <tr>
            <td></td>
            <td></td>
            
          <td colspan="2"><b>Total Amount</b></td>
          <td id="net" >0</td>
          <td class="pay"><a href="{% url 'shop:payment' %}">Pay Here</a></td>
         </tr>

       </table>

      



    </div>
  </div>
</section>
<script>
  const nodes = document.querySelectorAll('.amt');
  const arr = Array.from(nodes);
  const res = arr.reduce((acc, curr) => {
   return acc += Number(curr.textContent)
  }, 0);
  document.getElementById("net").innerHTML="Rs : "+res;

</script>

{% endblock content %}

shop/templates/shop/collections.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
Registration | shopkart
{% endblock title %}
{% block content %}

<section class="py-5 text-center container"  style="margin-top:70px;">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Bestsellers</h1>
      <p class="lead text-muted">Our most popular products based on sales. Updated hourly.</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Already User</a>
        <a href="#" class="btn btn-secondary my-2">Register</a>
      </p>
    </div>
  </div>
</section>
<section class="bg-light py-4 my-5" style="min-height:600px;">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3">Categories</h4>
        <hr style="border-color:#b8bfc2;">
        {% include 'shop/inc/message.html' %}
      </div>

      {% for item in catagory %}
      <div class="col-md-4 col-lg-3">
        <div class="card my-3">
          <img src="{{item.image.url}}" height="250px" width="250px" class="card-image-top" alt="Categories">
          <a href="{% url 'shop:collections' item.name %}">
          <div class="card-body">
            <h5 class="card-title text-primary">{{ item.name }}</h5>
            <p class="card-text">{{ item.description }}</p>
  
          </div>
        </a>
        </div>
      </div>
      {% endfor %}


    </div>
  </div>
</section>


{% endblock content %}

shop/templates/shop/inc/footer.html
<footer class="text-center text-lg-start bg-dark text-white">
    <section class="container d-flex justify-content-center justify-content-lg-between p-4">
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <div>
        <a href="" class="me-4 text-reset"><i class="fa fa-facebook"></i></a>
        <a href="" class="me-4 text-reset"><i class="fa fa-twitter"></i></a>
        <a href="https://shopkart-1a3g.onrender.com/" class="me-4 text-reset"><i class="fa fa-google"></i></a>
        <a href="" class="me-4 text-reset"><i class="fa fa-instagram"></i></a>
        <a href="" class="me-4 text-reset"><i class="fa fa-linkedin"></i></a>
        <a href="" class="me-4 text-reset"><i class="fa fa-github"></i></a>
      </div>
    </section>
  
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4"><i class="fa fa-cart-plus"></i> ShopKart</h6>
            <p>
              shopkart.com is a one stop destination for your family's fashion needs.
               We give you the opportunity to give your wardrobe a makeover with the latest collections from our top brands.
            </p>
          </div>
  
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">Make Money with Us</h6>
            <p><a href="#!" class="text-reset">Sell on ShopKart</a></p>
            <p><a href="#!" class="text-reset">Advertise Your Products</a></p>
            <p><a href="#!" class="text-reset">Become an Affiliate</a></p>
            <p><a href="#!" class="text-reset">Fulfilment by ShopKart</a></p>
          </div>
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">Useful links</h6>
            <p><a href="#!" class="text-reset">FAQ</a></p>
            <p><a href="#!" class="text-reset">Feedback</a></p>
            <p><a href="{% url 'shop:about' %}" class="text-reset">About Us</a></p>
            <p><a href="{% url 'shop:contact' %}" class="text-reset">Contact Us</a></p>
          </div>
          
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold mb-4"> Contact</h6>
            <p><i class="fa fa-home"></i> shopkart</p>
            <p><i class="fa fa-envelope"></i> shopkart@.com</p>
            <p><i class="fa fa-phone"></i> + 91 9043017689</p>
          </div>
  
        </div>
      </div>
    </section>
    <div class="text-center p-4">
      &copy;  2024 Copyright 
    </div>
  </footer>

shop/templates/shop/inc/message.html
{% for msg in messages %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
  {{msg}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

shop/templates/shop/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'shop:home' %}"><i class="fa fa-cart-plus"></i>shopkart</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
          <a class="nav-link" aria-current="page" href="{% url 'shop:home' %}"><i class="fa fa-home"></i> Home</a>
          {% if request.user.is_authenticated %}
          <a class="nav-link" aria-current="page" href="#"><i class="fa fa-user"></i> {{request.user}}</a>
          <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'shop:login' %}"><i class="fa fa-sign-in"></i> Login</a>
          <a class="nav-link" href="{% url 'shop:register' %}"><i class="fa fa-users"></i> Register</a>
        {% endif %}
          <a class="nav-link" href="{% url 'shop:collections' %}"><i class="fa fa-cubes"></i> Collections</a>
          <a class="nav-link" href="{% url 'shop:cart' %}"><i class="fa fa-shopping-cart"></i> Cart</a>
          <a class="nav-link" href="{% url 'shop:wishlist' %}"><i class="fa fa-shopping-cart"></i> Favourite</a>
          
          
          
      
        </div>
      </div>
    </div>
  </nav>

shop/templates/shop/index.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
shopkart | online shopping
{% endblock title %}

{% block content %}
{% include 'shop/inc/slider.html' %}
    <div class="container" style="margin-top: 70px;">
        <div class="row">
            <div class="col-12">
                <h4 class="mb-3">Lattest offers</h4>
                <hr style="border-color:#b8bfc2;">

            </div>
            {% for item in products %}
      <div class="col-md-4 col-lg-3">
        <div class="card my-3">
          <img src="{{item.product_image.url}}" style="height: 200px;"  class="card-image-top" alt="Categories">
          <a href="{% url 'shop:product_details' item.category.name item.name %}">
          <div class="card-body">
            <h5 class="card-title text-primary">{{ item.name }}</h5>
            <p class="card-text">
              <span class="float-start old_price"><s>Rs.{{ item.original_price | stringformat:'d'}}</s></span>
              <span class="float-end new_price">Rs.{{ item.selling_price | stringformat:'d' }}</span>
            </p>
          </div>
        </a>
        </div>
      </div>
      {% endfor %}
        </div>
    </div>
    {% endblock content %}

    

shop/templates/shop/products/index.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
ShopKart | Online Shopping
{% endblock title %}

{% block content %}
<section class="bg-light py-4 my-5" style="min-height:600px;">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3">{{category_name}} Products</h4>
        <hr style="border-color:#b8bfc2;">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'shop:home' %}">Home</a></li>
            <li class="breadcrumb-item active">{{category_name}} Collections</li>
          </ol>
        </nav>
        {% include 'shop/inc/message.html' %}
      </div>
      {% for item in products %}
      <div class="col-md-4 col-lg-3">
        <div class="card my-3">
          <a href="#"><img src="{{item.product_image.url}}" width="250px" height="250px"  class="card-image-top" alt="Categories"></a>
          <a href="{% url 'shop:product_details' category_name item.name %}">
          <div class="card-body">
            <h5 class="card-title text-primary">{{ item.name }}</h5>
            <p class="card-text">
              <span class="float-start old_price"><s>Rs.{{ item.original_price | stringformat:'d'}}</s></span>
              <span class="float-end new_price">Rs.{{ item.selling_price | stringformat:'d' }}</span>
            </p>
          </div>
        </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
 
{% endblock content %}

shop/templates/shop/products/product_details.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
ShopKart | Online Shopping
{% endblock title %}

{% block content %}
<style>
  /* .pic-box{
   position: relative;
  }
  .hot{
    background-color:orangered;
    color: white;
    width: 50px;
    font-weight: bold;
    display: inline;
    border-radius: 5px;
    padding: 5px;
    position: absolute;
    top: 20px;
    right: 0;


  } */
</style>
<section class="bg-light py-4 my-5" style="min-height:600px;">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3">  {{products}} Details</h4>
        <hr style="border-color:#b8bfc2;">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'shop:home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'shop:collections' products.category.name  %}">Collections</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{products}}</li>
          </ol>
        </nav>
        {% include 'shop/inc/message.html' %}
      </div>
      <div class="col-4 my-3 pic-box">
        {% if products.trending %}
          <div class="hot">Hot</div>
          {% endif %}
          <img src="{{products.product_image.url}}"  width="370px" height="300px" class="card-image-top" alt="{{products}}">
      </div>
      <div class="col-8 my-3">
          <h5 class="text-success">{{products | upper}}</h5>
          <p>{{products.vendor}}</p>
          <p>{{products.description}}</p>
          <h6 class="my-2 text-danger">Current Price : Rs. <s>{{products.original_price}}</s></h6>
          <h5 class="my-2 text-primary">Offer Price   : Rs.{{products.selling_price}}</h5>
          <div class="my-3">
            <form action="{% url 'shop:addtocart' products.id  %}" method="post">
            {% if products.quantity > 0 %}
            <input type="hidden" value="{{products.id}}" id="pid" name="quantity">
            
            {% csrf_token %}
            
              <p>
                <div class="input-group" style="width:150px">
                  <div class="input-group-text bg-success text-light" id="btnMinus" ><i class="fa fa-minus"></i></div>
                    <input type="text" name="qty" id="txtQty" value="1" class="form-control text-center">
                  <div class="input-group-text bg-success text-light" id="btnPlus"><i class="fa fa-plus"></i></div>
                </div>
              </p>
              
             
                {% csrf_token %}
             <button type="submit" class="btn btn-primary" id="btnCart" ><i class="fa fa-shopping-cart"></i> Add to Cart</button>
            </form>
            {% else %}
            <button class="btn btn-secondary"><i class="fa fa-minus"></i> Out of Stock</button>
            {% endif %}


            <form method="post" action="{% url 'shop:add_to_wishlist' products.id %}" >
              {% csrf_token %}
              <input type="hidden" value="{{products.id}}" id="wid" name="whislist">
              
             
              <button type="submit"  class="btn btn-danger" style="margin-top: 10px;" value="Add to Wishlist"  id="btnfav" ><i class="fa fa-heart"></i>wishlist</button>
          </form>

          <form method="post" action="#" >
            {% csrf_token %}
            <input type="hidden" value="{{products.id}}" id="wid" name="whislist">
            
           
            <a href="{% url 'shop:payment' %}" type="submit"  class="btn btn-primary" style="margin-top: 10px;" value="Add to payment"  id="btnpay" ><i class="fa fa-paypal"></i>Buy Now</a>
        </form>
          
            
          </div>
    
      </div>
    </div>
  </div>
</section>

 <script>
  document.addEventListener("DOMContentLoaded", function(event) {
  const btnPlus = document.getElementById("btnPlus");
  const btnMinus = document.getElementById("btnMinus");
  const txtQty = document.getElementById("txtQty");
  const pid = document.getElementById("pid");
  const btnCart = document.getElementById("btnCart");
  const btnFav = document.getElementById("btnFav");

  btnPlus.addEventListener("click", function() {
    let qty=parseInt(txtQty.value,10);
    qty=isNaN(qty)?0:qty;
    //console.log(qty);
    if(qty<10){
      qty++;
      txtQty.value=qty;
    }
  });

  btnMinus.addEventListener("click", function() {
      let qty=parseInt(txtQty.value,10);
      qty=isNaN(qty)?0:qty;
      //console.log(qty);
      if(qty>1){
        qty--;
        txtQty.value=qty;
      }
  });

  btnCart.addEventListener("click", function() {
      let qty=parseInt(txtQty.value,10);
      qty=isNaN(qty)?0:qty;
      
      if(qty>0){
        let postObj = { 
            'product_qty': qty, 
            'pid': pid.value
        }
        //console.log(postObj);
        fetch("/addtocart",{
          method: 'POST',
          credentials: 'same-origin',
          headers:{
              'Accept': 'application/json',
              'X-Requested-With': 'XMLHttpRequest',
              'X-CSRFToken': '{{ csrf_token }}',
          },
          body: JSON.stringify(postObj)
        }).then(response => {
	        return response.json();
        }).then(data => {
        	//console.log(data);
          alert(data['status']);
        });
 

      }else{
        alert("Please Enter The Quantity");
      }
      
  });


  btnFav.addEventListener("click", function() {
     
        let postObj = { 
            'pid': pid.value
        }
        console.log(postObj);
        fetch("/wishlist",{
          method: 'POST',
          credentials: 'same-origin',
          headers:{
              'Accept': 'application/json',
              'X-Requested-With': 'XMLHttpRequest',
              'X-CSRFToken': '{{ csrf_token }}',
          },
          body: JSON.stringify(postObj)
        }).then(response => {
	        return response.json();
        }).then(data => {
        	//console.log(data);
          alert(data['status']);
        });
      
  });


});
 </script>

{% endblock content %}

shop/templates/shop/register.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
  Registration | ShopKart
{% endblock title %}
{% block content %}
  <div class="container" style="margin-top:70px;min-height:600px;">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3"> New User Registration</h4>
        <hr style="border-color:#b8bfc2;">
        {% include 'shop/inc/message.html' %}
      </div>
    </div>
    <section class="py-4" >
      <div class="container">
        <div class="row">
          <div class="col-6">
            <form method="post" action="">
              {% csrf_token %}
              <div class="mb-4">
                <label for="" class="form-label">User Name</label>
                {{form.username}}
              </div>
              <div class="mb-4">
                <label for="" class="form-label">User Email</label>
                {{form.email}}
              </div>
              <div class="mb-4">
                <label for="" class="form-label">Password</label>
                {{form.password1}}
              </div>
              <div class="mb-4">
                <label for="" class="form-label">Confirm Password</label>
                {{form.password2}}
              </div>
              <button type="submit" class="btn btn-primary">Register</button>
            </form>
            <p class="my-2">Already user ? <a href="{% url 'shop:login' %}">Login Now</a> </p>
          </div>
          <div class="col-6">
            
                {% if form.errors.username %}
                  <label class="text-danger d-block">{{ form.errors.username }}</label>
                {% endif %}
            
                {% if form.errors.email %}
                <label class="text-danger d-block">{{ form.errors.email }}</label>
                {% endif %}
              
                {% if form.errors.password1 %}
                <label class="text-danger d-block">{{ form.errors.password1 }}</label>
                {% endif %}
              
                {% if form.errors.password2 %}
                <label class="text-danger d-block">{{ form.errors.password2 }}</label>
                {% endif %}
              
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

shop/templates/shop/wishlist.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
  Registration | ShopKart
{% endblock title %}
{% block content %}
  <section class="bg-light py-4 my-5" style="min-height:600px;">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h4 class="mb-3">Favourite Item</h4>
          <hr style="border-color:#b8bfc2;">
        </div>
      
        <table>
            <tr>
                <th>Image</th>
                <th>Product Name</th>
                <th>Unit</th>
                <th>Remove</th>
            </tr>
          

            {% for item in wishlist_items %}
           <tr>
              <td><img src="{{item.product.product_image.url}}" height="75px" alt="{{item.products.name}}"></td>
              <td>{{item.product.name}}</td>
              <td>{{item.product.selling_price | stringformat:'d'}}</td>
              <td><a href="{% url 'shop:remove_wishlist' item.id %}"  onclick="return confirm('Are you sure? to Remove')"  class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Remove</a></td> 
            </tr>
              
            {% endfor %}
            <tr>
        </table>
        
       
      </div>
      </div>
  </section>
{% endblock content %}